name: 'my_dbt_project'
version: '1.0.0'

profile: 'snowflake_dev'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

quoting:
  database: true
  schema: false
  identifier: false

clean-targets:     
  - "target"
  - "dbt_packages"

models:
  my_dbt_project:
    +quote_columns: true
    silver:
      +materialized: incremental
